// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDarX36ojc3DZLVm3lIOhwsyQvUCzYy8X4',
    appId: '1:41420884772:web:91550e6e206f036d8681b1',
    messagingSenderId: '41420884772',
    projectId: 'eden-farm-tech-test',
    authDomain: 'eden-farm-tech-test.firebaseapp.com',
    storageBucket: 'eden-farm-tech-test.appspot.com',
    measurementId: 'G-4GQ6J8CSGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYDoEd3LHq-6x_CQT9hZeyFVNpSyUrTJ8',
    appId: '1:41420884772:android:bf285ccf32811d2c8681b1',
    messagingSenderId: '41420884772',
    projectId: 'eden-farm-tech-test',
    storageBucket: 'eden-farm-tech-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASZ755fKjvcws4VA2_C-8hwV6WAPQxymQ',
    appId: '1:41420884772:ios:ad089df40879eeb48681b1',
    messagingSenderId: '41420884772',
    projectId: 'eden-farm-tech-test',
    storageBucket: 'eden-farm-tech-test.appspot.com',
    androidClientId: '41420884772-d1pru7in75kcpldbuc4h33skedu8tgtm.apps.googleusercontent.com',
    iosClientId: '41420884772-hj0m09m4e3od3v9t2734gfs7hcpf900b.apps.googleusercontent.com',
    iosBundleId: 'com.example.edenFarmTechTestHartono',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASZ755fKjvcws4VA2_C-8hwV6WAPQxymQ',
    appId: '1:41420884772:ios:ad089df40879eeb48681b1',
    messagingSenderId: '41420884772',
    projectId: 'eden-farm-tech-test',
    storageBucket: 'eden-farm-tech-test.appspot.com',
    androidClientId: '41420884772-d1pru7in75kcpldbuc4h33skedu8tgtm.apps.googleusercontent.com',
    iosClientId: '41420884772-hj0m09m4e3od3v9t2734gfs7hcpf900b.apps.googleusercontent.com',
    iosBundleId: 'com.example.edenFarmTechTestHartono',
  );
}
